---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  namespace: wallet
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: wallet
          image: 1234567891011.dkr.ecr.eu-west-2.amazonaws.com/wallet:latest
          env:
            - name: DOTNET_ENVIRONMENT
              value: production
            - name: SendGrid__SenderEmail
              value: "no-reply@myco.cloud"
            - name: SendGrid__SenderName
              value: "myco Cloud"
            - name: Wallet__SqsPhoneNumberUpdatedUrl
              value: https://sqs.eu-west-2.amazonaws.com/1234567891011/wallet_phonenumberupdated
            - name: Wallet__SqsPasswordUpdatedUrl
              value: https://sqs.eu-west-2.amazonaws.com/1234567891011/wallet_passwordupdated
            - name: Wallet__SqsUserReportsAvailableUrl
              value: https://sqs.eu-west-2.amazonaws.com/1234567891011/wallet_userreportsavailable
            - name: Wallet__SqsProvisionalUserCreatedUrl
              value: https://sqs.eu-west-2.amazonaws.com/1234567891011/wallet_provisionalusercreated
            - name: Wallet__SqsCustomerSentMessageUrl
              value: https://sqs.eu-west-2.amazonaws.com/1234567891011/wallet_customersentmessage
            - name: Wallet__SqsOssSentMessageUrl
              value: https://sqs.eu-west-2.amazonaws.com/1234567891011/wallet_osssentmessage
            - name: AWS_DEFAULT_REGION
              value: eu-west-2
            - name: Serilog__MinimumLevel__Default
              value: Information            
            - name: SendGrid__ApiKey
              valueFrom:
                secretKeyRef:
                  name: sendgrid
                  key: api-key
            - name: SendGrid__mycoCloudUrl
              value: https://myco.cloud/
