---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: decisioning
  namespace: decisioning
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1234567891011:role/eks-serviceacc-decisioning
